name: Run Random Image Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow

    - name: Run script
      run: python random_image.py

    - name: Upload image
      uses: actions/upload-artifact@v2
      with:
        name: random-image
        path: random_image.jpg
